### ISSUE TITLE
User without restricted-access role is being able to authenticate.

### ISSUE THREAD

**Issue by KhasDenis** [sventorben/keycloak-restrict-client-auth#224] opened 2023-12-05 12:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

User without restricted-access role is still being able to authenticate. Role itself created both in realm and client (In both cases there is 0 assignments). My current configuration is similar to this one https://user-images.githubusercontent.com/12183470/136276665-6b087651-baa9-43aa-addf-59db247529b7.png

<img width="1288" alt="Screenshot 2023-12-05 at 13 18 35" src="https://github.com/sventorben/keycloak-restrict-client-auth/assets/30524039/3cf83b65-3965-4d54-9960-5a139c27254b">

<img width="451" alt="Screenshot 2023-12-05 at 13 25 01" src="https://github.com/sventorben/keycloak-restrict-client-auth/assets/30524039/fee4b16a-fea2-4e24-a556-4dd063671873">

<img width="885" alt="Screenshot 2023-12-05 at 13 25 43" src="https://github.com/sventorben/keycloak-restrict-client-auth/assets/30524039/6955c832-45b2-4ec8-9499-ccdf1a935b38">

<img width="1052" alt="Screenshot 2023-12-05 at 13 27 35" src="https://github.com/sventorben/keycloak-restrict-client-auth/assets/30524039/50ca3176-0723-420d-8fc4-17c0873910b1">

### Expected Behavior

User without restricted-access role is not being able to authenticate.

### Version

```markdown
- Keycloak: 22.0.4
- This extension: 22.0.0
```

**Comment by sventorben** [comment] 2023-12-05 14:17
@KhasDenis If I see it correctly, you have mixed required and alternative flows on the same level which is not supported by Keycloak.
Try to make "Copy of browser forms 2" an alternative like the other ones and it should work.

**Comment by KhasDenis** [comment] 2023-12-05 14:29
Still being able to authenticate.
<img width="1235" alt="Screenshot 2023-12-05 at 15 25 26" src="https://github.com/sventorben/keycloak-restrict-client-auth/assets/30524039/652ca8a0-2554-415d-872f-b9012fe85d2d">

I was seeing issue with required and alternate on the same level before and usually it is in the logs something like 
`2023-12-05 12:10:41,478 WARN  [org.keycloak.authentication.DefaultAuthenticationFlow] (executor-thread-208) REQUIRED and ALTERNATIVE elements at same level! Those alternative executions will be ignored: [auth-cookie]
2023-12-05 12:10:41,479 WARN  [org.keycloak.services] (executor-thread-208) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException`

with the config I shared earlier there were no complains in the log.

**Comment by KhasDenis** [comment] 2023-12-05 15:26
<img width="1209" alt="Screenshot 2023-12-05 at 16 25 49" src="https://github.com/sventorben/keycloak-restrict-client-auth/assets/30524039/bda4d0a8-3e7e-44a5-88dd-7484c0af5422">

**Comment by KhasDenis** [comment] 2023-12-05 18:31
[realm-export.json](https://github.com/sventorben/keycloak-restrict-client-auth/files/13567570/realm-export.json)

**Comment by KhasDenis** [comment] 2023-12-06 12:39
If in "Copy of browser" flow I add explicit "Deny Access" right before "Restrict user authentication on client" I'm still able to authenticate. If I move "Deny Access" as a first step then I'm not able to authenticate.

Also as another test I created the same flow but with my js authenticator the same story.

So problem seems to be somewhere in the flow itself, but I don't see anything in the logs.

**Comment by KhasDenis** [comment] 2023-12-06 13:12
So it is basically this issue https://github.com/keycloak/keycloak/issues/10250

**Comment by sventorben** [comment] 2023-12-19 13:51
Have you checked your post login flow? See remark here: https://github.com/sventorben/keycloak-restrict-client-auth?tab=readme-ov-file#protect-all-possible-flows

**Comment by sventorben** [comment] 2024-01-02 17:07
Closing this issue, because this behaviour is caused by Keycloak itself and not by this extension.
It can be resolved by properly configuring post login flows.

**Closed by sventorben** 2024-01-02 17:07 UTC
Labels: bug, invalid
